name: readmore
description: A Flutter package than allow expand and collapse text dynamically
version: 2.2.0
homepage: https://github.com/jonataslaw/loadmore

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
